### ISSUE TITLE
OOM Error

### ISSUE THREAD

**Issue by liuhuasong** [sunng87/shake#5]
Hello, when type the following in lein REPL:
(require '[shake.static :as sh])
Then Error:
CompilerException java.lang.OutOfMemoryError: PermGen space, compiling:(shake/static.clj:17:1) 
Lib version:
Leiningen 2.1.3
[shake "0.4.0"]
[org.clojure/clojure "1.5.1"]
LEIN_JVM_OPTS:
-Xms128m -Xmx4096m -XX:PermSize=512m -XX:MaxPermSize=2048m -XX:+CMSClassUnloadingEnabled -XX:+UseParallelGC

**Comment by sunng87** [comment]
Seems you have too many executables in your path. Try `shake.dynamic` instead.
